import type { Activity, Flight, Hotel } from "@shared/schema";

export const mockActivities: Activity[] = [
  {
    id: "act-1",
    name: "Breakfast at Le Café",
    destinationId: "paris",
    category: "Food",
    image: "/images/breakfast-cafe.jpg",
    duration: "1h",
    price: 25,
    rating: 4.5,
    description: "Traditional French breakfast at a local café",
  },
  {
    id: "act-2",
    name: "Eiffel Tower Visit",
    destinationId: "paris",
    category: "Sightseeing",
    image: "/images/eiffel-tower.jpg",
    duration: "2h",
    price: 30,
    rating: 4.9,
    description: "Skip-the-line tickets to the iconic Eiffel Tower",
  },
  {
    id: "act-3",
    name: "Lunch at Traditional Bistro",
    destinationId: "paris",
    category: "Food",
    image: "/images/bistro-lunch.jpg",
    duration: "1.5h",
    price: 45,
    rating: 4.7,
    description: "Authentic French cuisine in a cozy bistro",
  },
  {
    id: "act-4",
    name: "Louvre Museum Tour",
    destinationId: "paris",
    category: "Culture",
    image: "/images/louvre.png",
    duration: "3h",
    price: 20,
    rating: 4.8,
    description: "Guided tour of the world's largest art museum",
  },
  {
    id: "act-5",
    name: "Seine River Cruise",
    destinationId: "paris",
    category: "Activity",
    image: "/images/river.png",
    duration: "2h",
    price: 40,
    rating: 4.6,
    description: "Romantic evening cruise along the Seine",
  },
];

export const mockFlights: Flight[] = [
  {
    id: "flight-1",
    airline: "Air France",
    from: "New York JFK",
    to: "Paris CDG",
    departureTime: "18:00",
    arrivalTime: "08:00+1",
    duration: "7h",
    price: 650,
    stops: 0,
    comfort: 4,
  },
  {
    id: "flight-2",
    airline: "United Airlines",
    from: "Los Angeles LAX",
    to: "Tokyo NRT",
    departureTime: "11:30",
    arrivalTime: "16:00+1",
    duration: "11h 30m",
    price: 850,
    stops: 0,
    comfort: 4,
  },
  {
    id: "flight-3",
    airline: "Delta",
    from: "New York JFK",
    to: "Paris CDG",
    departureTime: "22:00",
    arrivalTime: "12:00+1",
    duration: "7h",
    price: 480,
    stops: 1,
    comfort: 3,
  },
];

export const mockHotels: Hotel[] = [
  {
    id: "hotel-1",
    name: "Luxury Beach Resort",
    destinationId: "paris",
    image: "/assets/generated_images/Luxury_hotel_exterior_cac60dfd.png",
    rating: 4.8,
    reviewCount: 1240,
    price: 320,
    features: ["Free WiFi", "Breakfast Included", "Pool", "Central Location"],
    safety: 5,
    comfort: 5,
  },
  {
    id: "hotel-2",
    name: "Traditional Ryokan",
    destinationId: "tokyo",
    image: "/assets/generated_images/Japanese_ryokan_room_1e3385bc.png",
    rating: 4.9,
    reviewCount: 856,
    price: 280,
    features: ["Free WiFi", "Hot Springs", "High Safety", "Breakfast Included"],
    safety: 5,
    comfort: 4,
  },
  {
    id: "hotel-3",
    name: "Boutique City Hotel",
    destinationId: "paris",
    image: "/assets/generated_images/Luxury_hotel_exterior_cac60dfd.png",
    rating: 4.6,
    reviewCount: 542,
    price: 250,
    features: ["Free WiFi", "Rooftop Bar", "Gym", "24/7 Reception"],
    safety: 5,
    comfort: 4,
  },
];
